# Generated by Django 4.2.7 on 2024-06-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=50, verbose_name='Паспорт')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='День недели')),
                ('shift_start_time', models.TimeField(verbose_name='Время начала смены')),
                ('shift_end_time', models.TimeField(verbose_name='Время окончания смены')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=7, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.personalinformation', verbose_name='Персональная информация'),
        ),
        migrations.AddField(
            model_name='user',
            name='working_days',
            field=models.ManyToManyField(blank=True, null=True, to='users.workingday', verbose_name='Рабочие дни'),
        ),
    ]
