# Generated by Django 4.2.7 on 2024-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personalinformation_workingday_user_age_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Персональная информация', 'verbose_name_plural': 'Персональные информации'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Мастер'),
        ),
    ]
